In [213]:
#Declare a vector in Python using a list
v = [3,2]
print(v)

[3, 2]


In [214]:
#Declare a vector in Python using Numpy
import numpy as np 
v = np.array([3,2])
print(v)

[3 2]


In [215]:
# Declaring a three dimensional vector in Python using Numpy
import numpy as np 
v = np.array([4,1,2])
print(v)

[4 1 2]


In [216]:
# Declaring a five dimensional vector in Python using Numpy
import numpy as np 
v = np.array([6,1,5,8,3])
print(v)

[6 1 5 8 3]


In [217]:
# Adding two vectors in Python using Numpy
from numpy import array
v = array([3,2])
w = array([2,-1])

v_plus_w = v + w 

print(v_plus_w) #[5,1]

[5 1]


In [218]:
#Scaling a number in Python using Numpy
from numpy import array
v = array([3,1])

scaled_v = 2.0 * v

print(scaled_v) #[6,2]

[6. 2.]


In [219]:
# Matrix vector multiplication in NumPy
from numpy import array

# compose basis matrix with i-hat and j-hat
basis = array(
  [[3,0],
   [0,2]]
)

v = array([1,1])

new_v = basis.dot(v)

print(new_v) #[3,2]

[3 2]


In [220]:
# Separating the basis vectors and applying them as a transformation 
from numpy import array

i_hat = array([2,0])
j_hat = array([0,3])

basis = array([i_hat,j_hat]).transpose()

v = array([1,1])

new_v = basis.dot(v)

print(new_v) # [2,3]

[2 3]


In [221]:
# Transforming a vector using NumPy
from numpy import array

i_hat = array([2,0])
j_hat = array([0,3])

basis = array([i_hat, j_hat]).transpose()

v = array([2,1])

new_v = basis.dot(v)

print(new_v) # [4,3]

[4 3]


In [222]:
#A more complicated transformation 
from numpy import array

i_hat = array([2,3])
j_hat = array([2,-1])

basis = array([i_hat, j_hat]).transpose()

v = array([2,1])

new_v = basis.dot(v)

print(new_v) # [6,5]

[6 5]


In [223]:
# Combining two transformations
from numpy import array

# Transformation 1
i_hat1 = array([0,1])
j_hat1 = array([-1,0]) 
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1,0])
j_hat2 = array([1,1])
transform2 = array([i_hat2, j_hat2]).transpose()

v = array([1,2])

rotated = transform1.dot(v)
sheered = transform2.dot(rotated)
#combined = transform2 @ transform1
#print("COMBINED MATRIX:\n {}".format(combined))
#print(combined.dot(v))

print(sheered) # [-1,1]

[-1  1]


In [224]:
# Applying the transformation in reverse
from numpy import array

# Transformation 1
i_hat1 = array([0,1])
j_hat1 = array([-1,0]) 
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1,0])
j_hat2 = array([1,1])
transform2 = array([i_hat2, j_hat2]).transpose()

v = array([1,2])
combined = transform1 @ transform2

print("COMBINED MATRIX:\n {}".format(combined))
print(combined.dot(v))

COMBINED MATRIX:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


In [225]:
# Calculating a determinant 
from numpy.linalg import det
from numpy import array

i_hat = array([3,0])
j_hat = array([0,2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant) # print 6.0

6.0


In [226]:
# A determinant for a shear 
from numpy.linalg import det
from numpy import array 

i_hat = array([1,0])
j_hat = array([1,1])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant) # print 1.0

1.0


In [227]:
# A negative determinant
from numpy.linalg import det
from numpy import array 

i_hat = array([-2, 1])
j_hat = array([1, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant) # print -5.0

-5.000000000000001


In [228]:
# A determinant of zero
from numpy.linalg import det
from numpy import array 

i_hat = array([-2,1])
j_hat = array([3,-1.5])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant) # prints 0.0

0.0


In [229]:
# Using SymPy to study the inverse and identity matrix
from sympy import *

A = Matrix([
  [4,2,4],
  [5,3,7],
  [9,3,6]
])

inverse = A.inv()
identity = inverse * A

print("INVERSE: {}".format(inverse))

print("IDENTITY: {}".format(identity))


INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [230]:
# Using NumPy to solve a system of equations
from numpy import array
from numpy.linalg import inv

A = array([
  [4,2,4],
  [5,3,7],
  [9,3,6]
])

B = array([
  44,
  56,
  72
])

X = inv(A).dot(B)

print(X)

[ 2. 34. -8.]


In [231]:
# Using SymPy to solve a system of equations
from sympy import *

A = Matrix([
  [4,2,4],
  [5,3,7],
  [9,3,6]
])

B = Matrix([
  44,
  56,
  72
])

X = A.inv() * B

print(X)

Matrix([[2], [34], [-8]])


In [232]:
# Performing eigendecomposition in NumPy
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
  [1,2],
  [4,5]
])

eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)



EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [233]:
# Decomposiing and recomposing a matrix in NumPy
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
  [1,2],
  [4,5]
])

eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)

print("\nREBUILD MATRIX")
Q = eigenvecs
R = inv(Q)

L = diag(eigenvals)
B = Q @ L @ R

print(B)

EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]
